
'''
A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string s
 of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s

'''

# Solution

dna_string= ("TATCCCGCTAACCCCACTGTTAATTGAAGGGCCCGAGGAAGCAGATACTAGTCCGTCGAGAACTGAATTCATGGCAAGTCCGTTTGGCCACACTGCGGCAGATAAGAGGGGCCAAGCCTTGCTCTCATCCGACATATTTTAGCGCCGGCCTGGGATGGGCCCCGACTTTGTGTAAAAGGCGGGCGAGGTAGGACTACCATCTCGAACCTAAGGGGGCGATCGACTGGTGGTAGCGAGGCTGCGTGGTCAGCTGAGTATGCTGTGCTGTCTGTAGACTTGACCTAGTATTGCACGATATTGTCCGTAAGGTGTCTTGTTTCTTACAGATTGGAGCCGGCCAGTCGTTGATATAGCTAATATTTTCAAAGTGACAAGTGGACCTGGGGTTCCACTTCTGTCCCGTTGCCGAATGAGCGCAAATTAGGAGAGCCGGATTCGGATGATCGGCGTATTCATGGATCAGTATAAGACCCAATCTTTTCTCTAGGCCCCAAGACCACTCTCTATCGCATGTCAAAGCATTGATCGTGTAATAGTTGTATCAGCTCATTCTTCATTGGCACCCTTAATGACGCAGGATTCGGACGAGTGACGTTCATTGACTGGAGTGGATGGAAAGTCCTCGGCTATCCTAATTTGATCATCACTAACTCCCGTTTTTAAGGGGTCTGAATGGTCCTGCCTGATTCTCTGACTATAGCGGGGTCAAAGGACAATCCACAAAGTTCAGCTAAGATTTAAACATGCCCGTCGTGGTCTTTTTTAGCTCATAACAATCTGGGTTCCCCCGACAGAGTCTTTGTGATACACCACATTACCCACGTGGGTGGCCGAACTTAAAAGGGCATGCGGTGGACTTTTTAATGCCCGACTGAATGCAACACCATGCATTAGCCACAGTCCGTCAAGAGT")


nucleotides= {'A':0, 'C':0, 'G':0, 'T':0}
# Count occurrences of each nucleotide
for char in dna_string:
    if char in nucleotides:
      nucleotides[char] += 1
    else:
      print("invalid")
print(nucleotides["A"],nucleotides["C"],nucleotides["G"],nucleotides["T"])
